# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQptCSkv5pmNh-61nY2zx5mlwuZeLc8n
"""

# Intelligent Customer Support Chatbot (Simplified Example)
import random

def chatbot_response(user_input):
    responses = {
        "hello": "Hi there! How can I assist you today?",
        "issue": "I'm sorry to hear that you're facing an issue. Could you please describe it in more detail?",
        "refund": "I understand you'd like a refund. Please provide your order ID.",
        "bye": "Thank you for contacting support. Have a great day!",
    }

    # Basic keyword matching
    for keyword in responses:
        if keyword in user_input.lower():
            return responses[keyword]

    return "I'm not sure I understand. Could you please rephrase your question?"

# Output Display Simulation
print("Customer Support Chatbot\n---------------------------")
while True:
    user_input = input("You: ")
    if user_input.lower() in ["exit", "bye"]:
        print("Bot:", chatbot_response("bye"))
        break
    response = chatbot_response(user_input)
    print("Bot:", response)